% @Position/print_report: Print TPT report
function obj = print_report(obj, para_object)
  % A) Specify fieldnames <-> types key/value pairs
  tpt_map = struct(...
            'tpt_1', '1_Portfolio_identifying_data', ...
            'tpt_2', '2_Type_of_identification_code_for_the_fund_share_or_portfolio', ...
            'tpt_3', '3_Portfolio_name', ...
            'tpt_4', '4_Portfolio_currency_(B)', ...
            'tpt_5', '5_Net_asset_valuation_of_the_portfolio_or_the_share_class_in_portfolio_currency', ...
            'tpt_6', '6_Valuation_date', ...
            'tpt_7', '7_Reporting_date', ...
            'tpt_8', '8_Share_price', ...
            'tpt_8b', '8b_Total_number_of_shares', ...
            'tpt_9', '9_Cash_ratio', ...
            'tpt_10', '10_Portfolio_modified_duration', ...
            'tpt_11', '11_Complete_SCR_delivery', ...
            'tpt_12', '12_CIC_code_of_the_instrument', ...
            'tpt_13', '13_Economic_zone_of_the_quotation_place', ...
            'tpt_14', '14_Identification_code_of_the_instrument', ...
            'tpt_15', '15_Type_of_identification_code_for_the_instrument', ...
            'tpt_16', '16_Grouping_code_for_multiple_leg_instruments', ...
            'tpt_17', '17_Instrument_name', ...
            'tpt_17b', '17b_Asset_liability', ...
            'tpt_18', '18_Quantity', ...
            'tpt_19', '19_Nominal_amount', ...
            'tpt_20', '20_Contract_size_for_derivatives', ...
            'tpt_21', '21_Quotation_currency_(A)', ...
            'tpt_22', '22_Market_valuation_in_quotation_currency_(A)', ...
            'tpt_23', '23_Clean_market_valuation_in_quotation_currency_(A)', ...
            'tpt_24', '24_Market_valuation_in_portfolio_currency_(B)', ...
            'tpt_25', '25_Clean_market_valuation_in_portfolio_currency_(B)', ...
            'tpt_26', '26_Valuation_weight', ...
            'tpt_27', '27_Market_exposure_amount_in_quotation_currency_(A)', ...
            'tpt_28', '28_Market_exposure_amount_in_portfolio_currency_(B)', ...
            'tpt_29', '29_Market_exposure_amount_for_the_3rd_quotation_currency_(C)', ...
            'tpt_30', '30_Market_exposure_in_weight', ...
            'tpt_31', '31_Market_exposure_for_the_3rd_currency_in_weight_over_NAV', ...
            'tpt_32', '32_Interest_rate_type', ...
            'tpt_33', '33_Coupon_rate', ...
            'tpt_34', '34_Interest_rate_reference_identification', ...
            'tpt_35', '35_Identification_type_for_interest_rate_index', ...
            'tpt_36', '36_Interest_rate_index_name', ...
            'tpt_37', '37_Interest_rate_margin', ...
            'tpt_38', '38_Coupon_payment_frequency', ...
            'tpt_39', '39_Maturity_date', ...
            'tpt_40', '40_Redemption_type', ...
            'tpt_41', '41_Redemption_rate', ...
            'tpt_42', '42_Callable_putable', ...
            'tpt_43', '43_Call_put_date', ...
            'tpt_44', '44_Issuer_bearer_option_exercise', ...
            'tpt_45', '45_Strike_price_for_embedded_(call_put)_options', ...
            'tpt_46', '46_Issuer_name', ...
            'tpt_47', '47_Issuer_identification_code', ...
            'tpt_48', '48_Type_of_identification_code_for_issuer', ...
            'tpt_49', '49_Name_of_the_group_of_the_issuer', ...
            'tpt_50', '50_Identification_of_the_group', ...
            'tpt_51', '51_Type_of_identification_code_for_issuer_group', ...
            'tpt_52', '52_Issuer_country', ...
            'tpt_53', '53_Issuer_economic_area', ...
            'tpt_54', '54_Economic_sector', ...
            'tpt_55', '55_Covered_not_covered', ...
            'tpt_56', '56_Securitisation', ...
            'tpt_57', '57_Explicit_guarantee_by_the_country_of_issue', ...
            'tpt_58', '58_Subordinated_debt', ...
            'tpt_58b', '58b_Nature_of_the_tranche', ...
            'tpt_59', '59_Credit_quality_step', ...
            'tpt_60', '60_Call_Put_Cap_Floor', ...
            'tpt_61', '61_Strike_price', ...
            'tpt_62', '62_Conversion_factor_(convertibles)_concordance_factor_parity_(options)', ...
            'tpt_63', '63_Effective_date_of_instrument', ...
            'tpt_64', '64_Exercise_type', ...
            'tpt_65', '65_Hedging_rolling', ...
            'tpt_67', '67_CIC_of_the_underlying_asset', ...
            'tpt_68', '68_Identification_code_of_the_underlying_asset', ...
            'tpt_69', '69_Type_of_identification_code_for_the_underlying_asset', ...
            'tpt_70', '70_Name_of_the_underlying_asset', ...
            'tpt_71', '71_Quotation_currency_of_the_underlying_asset_(C)', ...
            'tpt_72', '72_Last_valuation_price_of_the_underlying_asset', ...
            'tpt_73', '73_Country_of_quotation_of_the_underlying_asset', ...
            'tpt_74', '74_Economic_area_of_quotation_of_the_underlying_asset', ...
            'tpt_75', '75_Coupon_rate_of_the_underlying_asset', ...
            'tpt_76', '76_Coupon_payment_frequency_of_the_underlying_asset', ...
            'tpt_77', '77_Maturity_date_of_the_underlying_asset', ...
            'tpt_78', '78_Redemption_profile_of_the_underlying_asset', ...
            'tpt_79', '79_Redemption_rate_of_the_underlying_asset', ...
            'tpt_80', '80_Issuer_name_of_the_underlying_asset', ...
            'tpt_81', '81_Issuer_identification_code_of_the_underlying_asset', ...
            'tpt_82', '82_Type_of_issuer_identification_code_of_the_underlying_asset', ...
            'tpt_83', '83_Name_of_the_group_of_the_issuer_of_the_underlying_asset', ...
            'tpt_84', '84_Identification_of_the_group_of_the_underlying_asset', ...
            'tpt_85', '85_Type_of_the_group_identification_code_of_the_underlying_asset', ...
            'tpt_86', '86_Issuer_country_of_the_underlying_asset', ...
            'tpt_87', '87_Issuer_economic_area_of_the_underlying_asset', ...
            'tpt_88', '88_Explicit_guarantee_by_the_country_of_issue_of_the_underlying_asset', ...
            'tpt_89', '89_Credit_quality_step_of_the_underlying_asset', ...
            'tpt_90', '90_Modified_duration_to_maturity_date', ...
            'tpt_91', '91_Modified_duration_to_next_option_exercise_date', ...
            'tpt_92', '92_Credit_sensitivity', ...
            'tpt_93', '93_Sensitivity_to_underlying_asset_price_(delta)', ...
            'tpt_94', '94_Convexity_gamma_for_derivatives', ...
            'tpt_94b', '94b_Vega', ...
            'tpt_95', '95_Identification_of_the_original_portfolio_for_positions_embedded_in_a_fund', ...
            'tpt_97', '97_SCR_mrkt_IR_up_weight_over_NAV', ...
            'tpt_98', '98_SCR_mrkt_IR_down_weight_over_NAV', ...
            'tpt_99', '99_SCR_mrkt_eq_type1_weight_over_NAV', ...
            'tpt_100', '100_SCR_mrkt_eq_type2_weight_over_NAV', ...
            'tpt_101', '101_SCR_mrkt_prop_weight_over_NAV', ...
            'tpt_102', '102_SCR_mrkt_spread_bonds_weight_over_NAV', ...
            'tpt_103', '103_SCR_mrkt_spread_structured_weight_over_NAV', ...
            'tpt_104', '104_SCR_mrkt_spread_derivatives_up_weight_over_NAV', ...
            'tpt_105', '105_SCR_mrkt_spread_derivatives_down_weight_over_NAV', ...
            'tpt_105a', '105a_SCR_mrkt_FX_up_weight_over_NAV', ...
            'tpt_105b', '105b_SCR_mrkt_FX_down_weight_over_NAV', ...
            'tpt_106', '106_Asset_pledged_as_collateral', ...
            'tpt_107', '107_Place_of_deposit', ...
            'tpt_108', '108_Participation', ...
            'tpt_110', '110_Valorisation_method', ...
            'tpt_111', '111_Value_of_acquisition', ...
            'tpt_112', '112_Credit_rating', ...
            'tpt_113', '113_Rating_agency', ...
            'tpt_114', '114_Issuer_economic_area', ...
            'tpt_115', '115_Fund_issuer_code', ...
            'tpt_116', '116_Fund_issuer_code_type', ...
            'tpt_117', '117_Fund_issuer_name', ...
            'tpt_118', '118_Fund_issuer_sector', ...
            'tpt_119', '119_Fund_issuer_group_code', ...
            'tpt_120', '120_Fund_issuer_group_code_type', ...
            'tpt_121', '121_Fund_issuer_group_name', ...
            'tpt_122', '122_Fund_issuer_country', ...
            'tpt_123', '123_Fund_CIC', ...
            'tpt_123a', '123a_Fund_custodian_country', ...
            'tpt_124', '124_Duration', ...
            'tpt_125', '125_Accrued_income_(Security Denominated Currency)', ...
            'tpt_126', '126_Accrued_income_(Portfolio Denominated Currency)', ...
            'tpt_127', '127_Bond_floor_(convertible_instrument_only)', ...
            'tpt_128', '128_Option_premium_(convertible_instrument_only)', ...
            'tpt_129', '129_Valuation_yield', ...
            'tpt_130', '130_Valuation_z_spread', ...
            'tpt_131', '131_Underlying_asset_category', ...
            'tpt_132', '132_Infrastructure_investment', ...
            'tpt_133', '133_custodian_name', ...
            'tpt_1000', '1000_tpt_Version' ...
               );
  % print attributes to report
% 0) open file
path_reports = strcat(para_object.path_working_folder,'/',para_object.folder_output,'/',para_object.folder_output_reports);
%TPT Naming Convention:     
%               YYYYMMDD_TPT_ISIN_YYYYMMDD_XXX = 
%               valuation date_TPT_identification code_reporting date_free text 
%               (example: 20170331_TPT_FR0123456789_20170415_XXX)
filename_TPT = strcat(path_reports,'/',datestr(obj.valuation_date,'yyyymmdd'), ...
                    '_TPT_',obj.port_id,'_',datestr(obj.reporting_date,'yyyymmdd'), ...
                    '_','octarisk','.csv');
fid = fopen (filename_TPT, 'w');
delim = ';';    
fields = fieldnames(tpt_map);
% 1) print header
header_string = '';
for ii = 1:1:length(fields)
    field = fields{ii};
    attr_name = getfield(tpt_map,field);
    header_string = strcat(header_string,delim,attr_name);
end
header_string = header_string(2:end); % remove first delimiter
fprintf(fid, '%s\n',header_string);  


% 2) print position data
for (ii=1:1:length(obj.positions))
    pos_obj = obj.positions(ii).object;
    pos_id = obj.positions(ii).id;
    if (isobject(pos_obj))
        print_string = '';
        for ii = 1:1:length(fields)
            field = fields{ii};
            if (( ii <= 12) || ( ii >= 118 && ii <= 124) || ( ii >= 126 && ii <= 130)) % take attributes from portfolio
                attr_value = any2str(obj.get(field));
                % check for date string and convert to TPT date format YYYY-MM-DD (code 29)
                if (ii == 6 || ii == 7) %valuation and reporting date
                    attr_value = datestr(attr_value,29);
                end
            else % take position attributes
                attr_value = any2str(pos_obj.get(field));
                % check for date string and convert to TPT date format YYYY-MM-DD
                if (ii == 41 || ii == 45 || ii == 67 || ii == 78) % more dates...
                    try 
                        attr_value = datestr(attr_value,29);
                    end
                end
            end
            print_string = strcat(print_string,delim,attr_value);
        end
        print_string = print_string(2:end); % remove first delimiter
        fprintf(fid, '%s\n',print_string); 
    end
end
        
% Close file
fclose (fid);
printf('%s: TPT report printed to file >>%s<<\n',obj.id,filename_TPT);
end   
