% setting attribute values
function obj = set(obj, varargin)
  % A) Specify fieldnames <-> types key/value pairs
  typestruct = struct(...
                'id', 'char', ...
                'name', 'char', ...
                'description', 'char', ...
                'type', 'char', ...
                'currency', 'char', ...
                'quantity', 'numeric', ...
                'positions', 'struct' , ... 
                'port_id', 'char', ...
                'value_mc', 'special' , ...
                'value_stress', 'special' , ...
                'value_base', 'numeric' , ...
                'exposure_base', 'numeric' , ...
                'exposure_stress', 'special' , ...
                'exposure_mc', 'special' , ...
                'timestep_mc', 'special' , ...
                'TPT_1', 'char', ...
                'TPT_2', 'char', ...
                'TPT_3', 'char', ...
                'TPT_4', 'char', ...
                'TPT_5', 'numeric', ...
                'TPT_6', 'date', ...
                'TPT_7', 'date', ...
                'TPT_8', 'numeric', ...
                'TPT_8b', 'numeric', ...
                'TPT_9', 'numeric', ...
                'TPT_10', 'numeric', ...
                'TPT_11', 'char', ...
                'TPT_12', 'char', ...
                'TPT_13', 'numeric', ...
                'TPT_14', 'char', ...
                'TPT_15', 'numeric', ...
                'TPT_16', 'char', ...
                'TPT_17', 'char', ...
                'TPT_17b', 'char', ...
                'TPT_18', 'numeric', ...
                'TPT_19', 'numeric', ...
                'TPT_20', 'numeric', ...
                'TPT_21', 'char', ...
                'TPT_22', 'numeric', ...
                'TPT_23', 'numeric', ...
                'TPT_24', 'numeric', ...
                'TPT_25', 'numeric', ...
                'TPT_26', 'numeric', ...
                'TPT_27', 'numeric', ...
                'TPT_28', 'numeric', ...
                'TPT_29', 'numeric', ...
                'TPT_30', 'numeric', ...
                'TPT_31', 'numeric', ...
                'TPT_32', 'char', ...
                'TPT_33', 'numeric', ...
                'TPT_34', 'char', ...
                'TPT_35', 'char', ...
                'TPT_36', 'char', ...
                'TPT_37', 'char', ...
                'TPT_38', 'numeric', ...
                'TPT_39', 'date', ...
                'TPT_40', 'char', ...
                'TPT_41', 'numeric', ...
                'TPT_42', 'char', ...
                'TPT_43', 'date', ...
                'TPT_44', 'char', ...
                'TPT_45', 'numeric', ...
                'TPT_46', 'char', ...
                'TPT_47', 'char', ...
                'TPT_48', 'numeric', ...
                'TPT_49', 'char', ...
                'TPT_50', 'char', ...
                'TPT_51', 'numeric', ...
                'TPT_52', 'char', ...
                'TPT_53', 'numeric', ...
                'TPT_54', 'char', ...
                'TPT_55', 'char', ...
                'TPT_56', 'char', ...
                'TPT_57', 'char', ...
                'TPT_58', 'char', ...
                'TPT_58b', 'char', ...
                'TPT_59', 'numeric', ...
                'TPT_60', 'char', ...
                'TPT_61', 'numeric', ...
                'TPT_62', 'numeric', ...
                'TPT_63', 'date', ...
                'TPT_64', 'char', ...
                'TPT_65', 'char', ...
                'TPT_67', 'char', ...
                'TPT_68', 'char', ...
                'TPT_69', 'numeric', ...
                'TPT_70', 'char', ...
                'TPT_71', 'char', ...
                'TPT_72', 'numeric', ...
                'TPT_73', 'char', ...
                'TPT_74', 'numeric', ...
                'TPT_75', 'numeric', ...
                'TPT_76', 'numeric', ...
                'TPT_77', 'date', ...
                'TPT_78', 'char', ...
                'TPT_79', 'numeric', ...
                'TPT_80', 'char', ...
                'TPT_81', 'char', ...
                'TPT_82', 'numeric', ...
                'TPT_83', 'char', ...
                'TPT_84', 'char', ...
                'TPT_85', 'numeric', ...
                'TPT_86', 'char', ...
                'TPT_87', 'numeric', ...
                'TPT_88', 'char', ...
                'TPT_89', 'numeric', ...
                'TPT_90', 'numeric', ...
                'TPT_91', 'numeric', ...
                'TPT_92', 'numeric', ...
                'TPT_93', 'numeric', ...
                'TPT_94', 'numeric', ...
                'TPT_94b', 'numeric', ...
                'TPT_95', 'char', ...
                'TPT_97', 'numeric', ...
                'TPT_98', 'numeric', ...
                'TPT_99', 'numeric', ...
                'TPT_100', 'numeric', ...
                'TPT_101', 'numeric', ...
                'TPT_102', 'numeric', ...
                'TPT_103', 'numeric', ...
                'TPT_104', 'numeric', ...
                'TPT_105', 'numeric', ...
                'TPT_105a', 'numeric', ...
                'TPT_105b', 'numeric', ...
                'TPT_106', 'numeric', ...
                'TPT_107', 'char', ...
                'TPT_108', 'numeric', ...
                'TPT_110', 'numeric', ...
                'TPT_111', 'numeric', ...
                'TPT_112', 'char', ...
                'TPT_113', 'char', ...
                'TPT_114', 'numeric', ...
                'TPT_115', 'char', ...
                'TPT_116', 'char', ...
                'TPT_117', 'char', ...
                'TPT_118', 'char', ...
                'TPT_119', 'char', ...
                'TPT_120', 'char', ...
                'TPT_121', 'char', ...
                'TPT_122', 'char', ...
                'TPT_123', 'char', ...
                'TPT_123a', 'char', ...
                'TPT_124', 'numeric', ...
                'TPT_125', 'numeric', ...
                'TPT_126', 'numeric', ...
                'TPT_127', 'numeric', ...
                'TPT_128', 'numeric', ...
                'TPT_129', 'numeric', ...
                'TPT_130', 'numeric', ...
                'TPT_131', 'char', ...
                'TPT_132', 'numeric', ...
                'TPT_133', 'char', ...
                'TPT_1000', 'char'
               );
  % B) store values in object
  if (length (varargin) < 2 || rem (length (varargin), 2) ~= 0)
    error ('Parameter.set: expecting property/value pairs');
  end
  
  while (length (varargin) > 1)
    prop = varargin{1};
    prop = lower(prop);
    val = varargin{2};
    varargin(1:2) = [];
    % check, if property is an existing field
    if (sum(strcmpi(prop,fieldnames(typestruct)))==0)
        fprintf('set: not an allowed fieldname >>%s<< with value >>%s<< :\n',prop,any2str(val));
        fieldnames(typestruct)
        error ('set: invalid property of %s class: >>%s<<\n',class(obj),prop);
    end
    % get property type:
    type = typestruct.(prop);
    % input checks and validation
    retval = return_checked_input(obj,val,prop,type);
    % store property in object
    obj.(prop) = retval;
  end
end   
