%# Copyright (C) 2019 Stefan Schlögl <schinzilord@octarisk.com>
%#
%# This program is free software; you can redistribute it and/or modify it under
%# the terms of the GNU General Public License as published by the Free Software
%# Foundation; either version 3 of the License, or (at your option) any later
%# version.
%#
%# This program is distributed in the hope that it will be useful, but WITHOUT
%# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
%# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
%# details.
%#
%# You should have received a copy of the GNU General Public License along with
%# this program; if not, see <http://www.gnu.org/licenses/>.
 
%# -*- texinfo -*-
%# @deftypefn {Function File} {[@var{score} ] =} get_informscore(@var{isocode})
%#
%# Map the ISO-2 currency code to INFORM risk score.
%# See https://drmkc.jrc.ec.europa.eu/inform-index/INFORM-Risk for further information.
%# Basic idea: if absolute needs (food, shelter, political stability, natural
%# desaster recovery) is not given, financial investments have to be closely
%# monitored. INFORM risk score delivers this classification in a condensed
%# way. 
%# @end deftypefn

function score = get_informscore(isocode)

if nargin < 1
    error('get_informscore: no country iso code provided.\n');
end

if nargin > 1
    fprintf('get_informscore: ignoring further argument(s).\n');
end
if ~(ischar(isocode))
    error('get_informscore: isocode not a string >>%s<<..\n',any2str(isocode));
end

% dictionary with all iso codes and their mapping to the INFORM risk score:

% manual update: map Hong Kong (HK) and Taiwan (TW) to China (CN)
if strcmpi(isocode,'TW') || strcmpi(isocode,'HK')
	isocode = 'CN';
end

% map iso-2 code to iso-3 code:
iso3 = map_country_isocodes(isocode);

% last update from INFORM Risk 2022 v0.6.1
inform = struct(   ...
        'AFG',8.2, ...
        'ALB',2.8, ...
        'DZA',4, ...
        'AGO',4.8, ...
        'ATG',2.1, ...
        'ARG',2.9, ...
        'ARM',5.4, ...
        'AUS',2.3, ...
        'AUT',1.7, ...
        'AZE',5.9, ...
        'BHS',2.2, ...
        'BHR',1.2, ...
        'BGD',5.7, ...
        'BRB',2, ...
        'BLR',1.8, ...
        'BEL',1.7, ...
        'BLZ',3.9, ...
        'BEN',4.5, ...
        'BTN',3.1, ...
        'BOL',4.2, ...
        'BIH',3.5, ...
        'BWA',3.1, ...
        'BRA',4.9, ...
        'BRN',1.7, ...
        'BGR',2.5, ...
        'BFA',6.4, ...
        'BDI',5.9, ...
        'CPV',2.2, ...
        'KHM',4.6, ...
        'CMR',6.1, ...
        'CAN',2.4, ...
        'CAF',7.8, ...
        'TCD',7.9, ...
        'CHL',3.6, ...
        'CHN',4.1, ...
        'COL',5.4, ...
        'COM',3.8, ...
        'COG',5.4, ...
        'COD',7.6, ...
        'CRI',3.2, ...
        'CIV',5.4, ...
        'HRV',2.3, ...
        'CUB',2.4, ...
        'CYP',2.9, ...
        'CZE',1.1, ...
        'DNK',1.1, ...
        'DJI',5.2, ...
        'DMA',3, ...
        'DOM',4.3, ...
        'ECU',4.5, ...
        'EGY',4.7, ...
        'SLV',4.6, ...
        'GNQ',3.7, ...
        'ERI',5.8, ...
        'EST',0.8, ...
        'SWZ',3.6, ...
        'ETH',6.8, ...
        'FJI',2.8, ...
        'FIN',0.9, ...
        'FRA',2.2, ...
        'GAB',3.6, ...
        'GMB',3.9, ...
        'GEO',3.7, ...
        'DEU',1.9, ...
        'GHA',4.3, ...
        'GRC',2.8, ...
        'GRD',1.9, ...
        'GTM',5.3, ...
        'GIN',4.6, ...
        'GNB',4.4, ...
        'GUY',3.9, ...
        'HTI',6.2, ...
        'HND',5.3, ...
        'HUN',1.8, ...
        'ISL',1.3, ...
        'IND',5.2, ...
        'IDN',4.6, ...
        'IRN',4.7, ...
        'IRQ',6.6, ...
        'IRL',1.5, ...
        'ISR',2.4, ...
        'ITA',2.4, ...
        'JAM',3.1, ...
        'JPN',2.2, ...
        'JOR',4.4, ...
        'KAZ',1.8, ...
        'KEN',5.7, ...
        'KIR',3.8, ...
        'PRK',4.2, ...
        'KOR',1.9, ...
        'KWT',1.8, ...
        'KGZ',3.3, ...
        'LAO',4.1, ...
        'LVA',1.4, ...
        'LBN',4.9, ...
        'LSO',4.1, ...
        'LBR',5.4, ...
        'LBY',6.2, ...
        'LIE',0.8, ...
        'LTU',1.2, ...
        'LUX',0.9, ...
        'MDG',5.1, ...
        'MWI',4.7, ...
        'MYS',3.1, ...
        'MDV',2.3, ...
        'MLI',7, ...
        'MLT',1.9, ...
        'MHL',3.6, ...
        'MRT',5.1, ...
        'MUS',1.9, ...
        'MEX',4.9, ...
        'FSM',3.6, ...
        'MDA',2.8, ...
        'MNG',2.6, ...
        'MNE',2.3, ...
        'MAR',3.7, ...
        'MOZ',7.2, ...
        'MMR',6.3, ...
        'NAM',3.9, ...
        'NRU',3.2, ...
        'NPL',5, ...
        'NLD',1.3, ...
        'NZL',1.6, ...
        'NIC',4.7, ...
        'NER',7.4, ...
        'NGA',6.5, ...
        'MKD',2.3, ...
        'NOR',1, ...
        'OMN',2.5, ...
        'PAK',5.9, ...
        'PLW',2.8, ...
        'PSE',4.5, ...
        'PAN',3.8, ...
        'PNG',5.9, ...
        'PRY',2.9, ...
        'PER',4.8, ...
        'PHL',5.3, ...
        'POL',1.6, ...
        'PRT',1.6, ...
        'QAT',1.5, ...
        'ROU',2.4, ...
        'RUS',3.5, ...
        'RWA',4.5, ...
        'KNA',1.9, ...
        'LCA',2.2, ...
        'VCT',2.6, ...
        'WSM',3.1, ...
        'STP',2.5, ...
        'SAU',2.7, ...
        'SEN',4.3, ...
        'SRB',3, ...
        'SYC',1.8, ...
        'SLE',5.2, ...
        'SGP',0.5, ...
        'SVK',1.5, ...
        'SVN',1.2, ...
        'SLB',4.5, ...
        'SOM',8.8, ...
        'ZAF',4.5, ...
        'SSD',8.4, ...
        'ESP',2.1, ...
        'LKA',3.6, ...
        'SDN',6.4, ...
        'SUR',3.3, ...
        'SWE',1.4, ...
        'CHE',1.4, ...
        'SYR',7.1, ...
        'TJK',4.4, ...
        'TZA',5.3, ...
        'THA',3.8, ...
        'TLS',4.3, ...
        'TGO',4.8, ...
        'TON',3.5, ...
        'TTO',2.6, ...
        'TUN',3.3, ...
        'TUR',4.9, ...
        'TKM',2.4, ...
        'TUV',3.4, ...
        'UGA',6, ...
        'UKR',4.5, ...
        'ARE',1.7, ...
        'GBR',1.9, ...
        'USA',3.4, ...
        'URY',1.8, ...
        'UZB',3.1, ...
        'VUT',4.4, ...
        'VEN',4.7, ...
        'VNM',3.7, ...
        'YEM',8.2, ...
        'ZMB',4.2, ...
        'ZWE',5.1
            );
                       
if ~(isfield(inform,upper(iso3)))
    error('get_informscore: no valid country iso code >>%s<< provided.\n',iso3);
end                       
% map the string to the number 1:length(dcc_cell):
score = getfield(inform,upper(iso3));
end 


%!assert(get_informscore('DE'),1.9)
